server:
  servlet:
    context-path: '/api'

auth0:
  audience: https://api.dawn.watch/api/actuator/health

spring:
  data:
    mongodb:
      autoIndexCreation: true
      uri: mongodb://admin:bas1cPa22@localhost:27017/
      database: nft-cache
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-8cfuc6dy5gmdhotp.us.auth0.com/

  cache:
    jcache:
      config: 'classpath:ehcache.xml'
#
logging:
  level:
    org:
      springframework:
        cache: 'INFO'
        data:
          mongodb: 'INFO'
        security: 'DEBUG'
    com:
      nfttv:
        apis: 'DEBUG'
